### ISSUE TITLE
callbacks.py里面import backend和objectives等包报错是否是因为数据集没整理好？

### ISSUE THREAD

**Issue by haojingzi** [XPixelGroup/HAT#14]
`import backend as K
import objectives as obj
from generators import BaseGenerator
import serializations
import metrics
from abc import ABCMeta, abstractmethod
import pickle
import matplotlib.pyplot as plt
import numpy as np
import time
from supports import to_list, format_data_list, print_or_logging
import sys
from inspect import isfunction`

代码提示没有错误，一运行会出现类似ModuleNotFoundError: No module named 'objectives'的错误
pip在命令行安装包和库，有的可以安装，有的安装不上找不到
代码没提示错误，运行就会报错是否和数据集或者模型有关，而不是和pip install在命令里安装有关？

**Comment by chxy95** [comment]
@haojingzi 应该是环境没有配置好

**Comment by haojingzi** [comment]
![image](https://user-images.githubusercontent.com/112917280/188779652-2222a31d-a147-4044-929b-d53b22e13205.png)
请问有关hat的包安装完了，import data和arch下面有红线有问题报错，这会耽误网络吗？
我简单测试了一下还是能够能够出结果的

**Comment by AdddCharm** [comment]
你好。这个问题解决了吗?

**Comment by Syx20021** [comment]
如何解决objectives的问题的老哥，麻烦教一下

**Comment by LinYuxiang-debug** [comment]
怎么解决objectives的问题

**Comment by SnageGao** [comment]
这个包在keras里面，需要下载对应的keras和tensorflow

**Comment by buxuewushu1314** [comment]
> 如何解决objectives的问题的老哥，麻烦教一下

python版本问题，回退到python3.8，backend、objectives、generators 问题都能解决。

**Comment by 409316492** [comment]
(image_SR) PS D:\Users\CPM\PycharmProjects\HAT-main> python -V
Python 3.8.19
(image_SR) PS D:\Users\CPM\PycharmProjects\HAT-main> python hat/test.py -opt options/test/HAT_SRx4_ImageNet-pretrain.yml
Traceback (most recent call last):
  File "hat/test.py", line 4, in <module>
    import hat.archs
  File "D:\Users\CPM\anaconda3\envs\image_SR\lib\site-packages\hat\__init__.py", line 2, in <module>
    from . import callbacks
  File "D:\Users\CPM\anaconda3\envs\image_SR\lib\site-packages\hat\callbacks.py", line 8, in <module>
    import objectives as obj
ModuleNotFoundError: No module named 'objectives'

没用
