### ISSUE TITLE
out of memory on testing

### ISSUE THREAD

**Issue by ziippy** [XPixelGroup/HAT#18]
I set the batch size to 2 during training and it works fine.
I am using the V100 16G GPU card just one.
However, when I tried to test, it resulted in "out of memory" CUDA errors

[
2022-09-21 08:54:33,454 INFO: Model [HATModel] is created.
2022-09-21 08:54:33,455 INFO: Testing open...
Traceback (most recent call last):
  File "/mnt/disk2/HAT/hat/test.py", line 11, in <module>
    test_pipeline(root_path)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/basicsr/test.py", line 40, in test_pipeline
    model.validation(test_loader, current_iter=opt['name'], tb_logger=None, save_img=opt['val']['save_img'])
  File "/home/ubuntu/venv/lib/python3.10/site-packages/basicsr/models/base_model.py", line 48, in validation
    self.nondist_validation(dataloader, current_iter, tb_logger, save_img)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/basicsr/models/sr_model.py", line 157, in nondist_validation
    self.test()
  File "/mnt/disk2/HAT/hat/models/hat_model.py", line 29, in test
    self.output = self.net_g(img)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/disk2/HAT/hat/archs/hat_arch.py", line 978, in forward
    x = self.conv_after_body(self.forward_features(x)) + x
  File "/mnt/disk2/HAT/hat/archs/hat_arch.py", line 964, in forward_features
    x = layer(x, x_size, params)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/disk2/HAT/hat/archs/hat_arch.py", line 619, in forward
    return self.patch_embed(self.conv(self.patch_unembed(self.residual_group(x, x_size, params), x_size))) + x
  File "/home/ubuntu/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/disk2/HAT/hat/archs/hat_arch.py", line 530, in forward
    x = self.overlap_attn(x, x_size, params['rpi_oca'])
  File "/home/ubuntu/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/disk2/HAT/hat/archs/hat_arch.py", line 425, in forward
    attn = attn + relative_position_bias.unsqueeze(0)
RuntimeError: CUDA out of memory. Tried to allocate 3.38 GiB (GPU 0; 15.78 GiB total capacity; 6.44 GiB already allocated; 1.18 GiB free; 13.45 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
]

How can I solve it?

**Comment by chxy95** [comment]
I will add a tile module to deal with the OOM problem in these two days soon.

**Comment by ziippy** [comment]
> I will add a tile module to deal with the OOM problem in these two days soon.

Thanks. I will wait for you.

**Comment by chxy95** [comment]
The tile mode is provided for limited GPU memory when testing. The setting can be referred to https://github.com/XPixelGroup/HAT/blob/39eeb5c28741b05ed2f23f13ff9131efe7539fde/options/test/HAT_tile_example.yml#L7-L9

**Comment by ziippy** [comment]
Oh!!! It works.

output like that
2022-09-25 20:49:05,012 INFO: Testing open...
        Tile 1/4
        Tile 2/4
        Tile 3/4
        Tile 4/4
        Tile 1/4
        Tile 2/4
        Tile 3/4
        Tile 4/4
        Tile 1/4
        Tile 2/4
        Tile 3/4
        Tile 4/4
        Tile 1/4
        Tile 2/4
        Tile 3/4
        ...

Thanks!!!
