### ISSUE TITLE
Inference not working

### ISSUE THREAD

**Issue by AndreiBaraian** [XPixelGroup/HAT#54]
Hi!

Thanks for the excellent work! I was trying to run a pretrained HAT GAN model on my data, but I came across this error:

2023-03-20 15:26:00,113 INFO: Model [HATModel] is created.
2023-03-20 15:26:00,113 INFO: Testing custom...
Traceback (most recent call last):
  File "hat/test.py", line 11, in <module>
    test_pipeline(root_path)
  File "/home/user/anaconda3/envs/hat/lib/python3.8/site-packages/basicsr/test.py", line 40, in test_pipeline
    model.validation(test_loader, current_iter=opt['name'], tb_logger=None, save_img=opt['val']['save_img'])
KeyError: 'val'

I ahve torch 1.7.1 and the basicsr 1.3.4.9. The command I've used to run the the inference was `python hat/test.py -opt options/test/HAT_GAN_Real_SRx4.yml`

Thanks!

**Comment by chxy95** [comment]
@AndreiBaraian This option has just been updated. You may try again.

**Comment by AndreiBaraian** [comment]
@chxy95 Works!! Thanks a million! I've tested it in the chaiNNer as well, impressive work.
