### ISSUE TITLE
Could I ask about train SRx4 I have some error?

### ISSUE THREAD

**Issue by nk960106** [XPixelGroup/HAT#90]
When I want to train HAT SRx4, I use train_HAT_SRx4_finetune_from_SRx2.yml but I got some error like:

2023-08-15 18:56:07,254 INFO: Loading HAT model from ./experiments/HAT_SRx2.pth, with param key: [params_ema].
2023-08-15 18:56:07,300 WARNING: Current net - loaded net:
2023-08-15 18:56:07,301 WARNING:   upsample.2.bias
2023-08-15 18:56:07,301 WARNING:   upsample.2.weight
2023-08-15 18:56:07,301 WARNING: Loaded net - current net:
Traceback (most recent call last):
  File "hat/train.py", line 11, in <module>
    train_pipeline(root_path)
  File "/home/u73/.local/lib/python3.8/site-packages/basicsr/train.py", line 124, in train_pipeline
    model = build_model(opt)
  File "/home/u73/.local/lib/python3.8/site-packages/basicsr/models/__init__.py", line 27, in build_model
    model = MODEL_REGISTRY.get(opt['model_type'])(opt)
  File "/home/u73/.local/lib/python3.8/site-packages/basicsr/models/sr_model.py", line 30, in __init__
    self.load_network(self.net_g, load_path, self.opt['path'].get('strict_load_g', True), param_key)
  File "/home/u73/.local/lib/python3.8/site-packages/basicsr/models/base_model.py", line 303, in load_network
    net.load_state_dict(load_net, strict=strict)
  File "/home/u73/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for HAT:
        Missing key(s) in state_dict: "upsample.2.weight", "upsample.2.bias".

May I inquire about how to address this error?  Or is there someone who can provide assistance?

**Comment by chxy95** [comment]
@chxy95 Set strict_load=False.

**Comment by nk960106** [comment]
It's working perfectly now. Thank you very much.
